version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large

    steps:
      - run:
          name: Setup packages
          command: |
            sudo DEBIAN_FRONTEND=noninteractive apt-get update -yqq
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -yqq bc bison build-essential curl ccache coreutils flex g++-multilib gcc-multilib git gnupg \
            libxml2 lib32z1-dev liblz4-tool libncurses5-dev lzop zip zlib1g-dev wget libssl-dev libxml2-utils lld gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev unzip ca-certificates rsync python-is-python3 zstd jq libarchive-tools
      - run:
          name: Clone kernel repo
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
            git config --global user.email "${CIRCLE_PROJECT_USERNAME}@gmail.com"
            git clone ${KERNEL_REPO} -b ${KERNEL_BRANCH} --depth=500 kernel
          environment:
            KERNEL_REPO: https://GitLab.com/MT6768Lab/KernelTree.git
            KERNEL_BRANCH: 14
      - run:
          name: Build
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/kernel
            wget https://raw.githubusercontent.com/${CIRCLE_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/config.env
            wget https://raw.githubusercontent.com/${CIRCLE_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/kranul-build.sh && chmod +x ./kranul-build.sh
            echo "Setting up ccache"
            sudo mkdir -p /mnt/ccache $CIRCLE_WORKING_DIRECTORY/ccache
            sudo mount --bind $CIRCLE_WORKING_DIRECTORY/ccache /mnt/ccache
            export USE_CCACHE=1 && export CCACHE_EXEC=$(which ccache) && ccache -M 10G && export CCACHE_DIR=/mnt/ccache
            echo "Building kernel"
            ./kranul-build.sh
